<?php
/**
 * Config form include
 *
 * Included in the configuration page for the plugin to change settings.
 *
 * @package OaiPmhRepository
 * @author John Flatness, Yu-Hsun Lin
 * @copyright Copyright 2009-2014 John Flatness, Yu-Hsun Lin
 * @license http://www.gnu.org/licenses/gpl-3.0.txt
 */
?>

<div class="field">
    <div class="two columns alpha">
        <label for="oaipmh_repository_name">Repository name</label>
    </div>
    <div class="inputs five columns omega">
        <p class="explanation">Name for this OAI-PMH repository.</p>
        <?php echo $this->formText('oaipmh_repository_name', $this->settings()->get('oaipmh_repository_name'));?>
    </div>
</div>
<div class="field">
    <div class="two columns alpha">
        <label for="oaipmh_repository_namespace_id">Namespace identifier</label>
    </div>
    <div class="inputs five columns omega">
        <p class="explanation">This will be used to form
        globally unique IDs for the exposed metadata items.  This value is required
        to be a domain name you have registered.  Using other values will generate
        invalid identifiers.</p>
        <?php echo $this->formText('oaipmh_repository_namespace_id', $this->settings()->get('oaipmh_repository_namespace_id'));?>
    </div>
</div>
<div class="field">
    <div class="two columns alpha">
        <label for="oaipmh_repository_expose_files">Expose files</label>
    </div>
    <div class="inputs five columns omega">
        <p class="explanation">Whether the plugin should include identifiers for the
        files associated with items.  This provides harvesters with direct access to
        files.</p>
        <?php echo $this->formCheckbox('oaipmh_repository_expose_files', $this->settings()->get('oaipmh_repository_expose_files')); ?>
    </div>
</div>
